name: Weekly Scrape

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Run scraping script
        env:
          NEXTBUS_API_URL: ${{ secrets.NEXTBUS_API_URL }}
          NEXTBUS_BASIC_AUTH: ${{ secrets.NEXTBUS_BASIC_AUTH }}
        run: python scripts/scrape.py

      - name: Commit and push any changes
        run: |
          git diff --exit-code || {
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "gh-actions: update routes & stops"
            git push
          }
